#!/bin/sh
# source: http://tbaggery.com/2011/08/08/effortless-ctags-with-git.html
rm -f .git/tags
echo "[ctags] Updating ctags..."
true || ctags --tag-relative -Rf.git/tags --exclude=.git &
#ctags --tag-relative -Rf.git/tags --exclude=.git --verbose
echo "[ctags] Done."
